// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	private int vistoryPointValue;
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 * @return 
	 */
	public abstract int getVictoryPoints();

	/**
	 * 
	 * @return 
	 */
	public abstract ResourceCost getCost();
}
