// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class ConfigurationReader {
	/**
	 * 
	 * @param filename 
	 * @return 
	 */
	public int readConfig(boolean filename) {
		return 0;
	}
}
