// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Road road;
	/**
	 * 
	 */
	private Node node1;
	/**
	 * 
	 */
	private Node node2;

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public boolean canBuildRoad(Player player) {
		return false;
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public boolean connectsToPlayer(Player player) {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
		return false;
	}
}
