// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private Node[] adjecentNodes;
	/**
	 * 
	 */
	private Tile[] adjecentTiles;

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public boolean canBuildSettlement(Player player) {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canUpgradeToCity() {
		return false;
	}

	/**
	 * 
	 * @param building 
	 */
	public void placeBuilding(Building building) {
	}

	/**
	 * 
	 * @return 
	 */
	public Building getBuilding() {
		return building;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
		return false;
	}
}
