// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class ResourceCost {
	/**
	 * 
	 */
	private int wood = 0;
	/**
	 * 
	 */
	private int brick = 0;
	/**
	 * 
	 */
	private int sheep = 0;
	/**
	 * 
	 */
	private int wheat = 0;
	/**
	 * 
	 */
	private int ore = 0;

	/**
	 * 
	 * @param hand 
	 * @return 
	 */
	public boolean canAfford(ResourceHand hand) {
		return false;
	}

	/**
	 * 
	 * @param hand 
	 */
	public void deductFrom(ResourceHand hand) {
	}
}
