// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	private int wood = 0;
	/**
	 * 
	 */
	private int brick = 0;
	/**
	 * 
	 */
	private int sheep = 0;
	/**
	 * 
	 */
	private int ore = 0;
	/**
	 * 
	 */
	private int wheat = 0;

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void addResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean removeResource(ResourceType type, int amount) {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public int getTotalCards() {
		return brick;
	}

	/**
	 * 
	 */
	public void clear() {
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean hasResources(ResourceCost cost) {
		return false;
	}
}
