// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 * @return 
	 */
	public ResourceCost getCost() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}
}
