// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int numberToken;
	/**
	 * 
	 */
	private boolean hasRobber = false;

	/**
	 * 
	 * @return 
	 */
	public ResourceType produceResource() {
		return resourceType;
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
		return id;
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumberToken() {
		return numberToken;
	}
}
