/**
 * Demonstrator class for Settlers of Catan Simulator
 * 
 * This class demonstrates the key functionality of the simulator as required by R1.9.
 * It creates a game instance, optionally loads configuration, and runs a simulation.
 * 
 * Key features demonstrated:
 * - R1.1: Board initialization with tiles, nodes, and edges
 * - R1.2: Four randomly acting agents
 * - R1.3: Following game rules (simplified, without harbors, development cards, robber)
 * - R1.4: User-defined number of rounds (via config file) or until 10 VP
 * - R1.5: Halting on termination conditions
 * - R1.6: Respecting invariants (distance rules, connections)
 * - R1.7: Logging actions and victory points
 * - R1.8: Players with >7 cards try to build
 * 
 * @author Generated by Claude AI from UML diagram
 * @version 1.0
 */
public class Demonstrator {
    
    public static void main(String[] args) {
        System.out.println("=" .repeat(60));
        System.out.println("  SETTLERS OF CATAN SIMULATOR");
        System.out.println("  Software Design I - Assignment 1");
        System.out.println("=" .repeat(60));
        System.out.println();
        
        // Create the game simulator
        // This initializes the board, 4 players, dice, and logger
        GameSimulator simulator = new GameSimulator();
        
        // Optional: Load configuration from file
        // Format: "turns: <number>" where number is 1-8192
        // If no config file is provided, uses default of 100 rounds
        if (args.length > 0) {
            System.out.println("Loading configuration from: " + args[0]);
            simulator.loadConfig(args[0]);
        } else {
            System.out.println("No configuration file provided.");
            System.out.println("Using default: 100 rounds maximum");
            System.out.println("(To use config file: java Demonstrator config.txt)");
        }
        
        System.out.println();
        System.out.println("Initializing game...");
        System.out.println();
        
        // Run the simulation
        // This will:
        // 1. Initialize the board with 19 tiles (R1.1)
        // 2. Create adjacencies between tiles, nodes, and edges
        // 3. Perform initial placements (2 settlements + 2 roads per player)
        // 4. Run the main game loop until:
        //    - A player reaches 10 victory points, OR
        //    - Maximum rounds is reached (R1.4, R1.5)
        // 5. Each turn:
        //    - Roll dice (R1.7 - logged)
        //    - Collect resources (if not 7)
        //    - Attempt to build (roads, settlements, cities)
        //    - Check if player has >7 cards and try to build (R1.8)
        // 6. Log victory points at end of each round (R1.7)
        // 7. Print final game state
        
        simulator.runSimulation();
        
        System.out.println();
        System.out.println("=" .repeat(60));
        System.out.println("  SIMULATION COMPLETE");
        System.out.println("=" .repeat(60));
        
        // Demonstrate invariants being respected (R1.6):
        System.out.println("\nKey Invariants Demonstrated:");
        System.out.println("- New roads connected to existing roads or settlements");
        System.out.println("- Cities replace existing settlements");
        System.out.println("- Distance rule: settlements/cities at least 2 nodes apart");
        System.out.println("- Players cannot build without sufficient resources");
        
        // Additional demonstration: Show that we can run multiple simulations
        System.out.println("\n--- Running Second Simulation (shortened) ---");
        GameSimulator simulator2 = new GameSimulator();
        // We could set a different max rounds here
        System.out.println("(This demonstrates that the simulator is reusable)");
    }
    
    /**
     * Helper method to create a sample configuration file
     * This can be used for testing
     */
    public static void createSampleConfig(String filename) {
        try {
            java.io.FileWriter writer = new java.io.FileWriter(filename);
            writer.write("turns: 50\n");
            writer.close();
            System.out.println("Created sample config file: " + filename);
        } catch (java.io.IOException e) {
            System.err.println("Error creating config file: " + e.getMessage());
        }
    }
}
