// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class ActionLogger {
	/**
	 * 
	 * @param round 
	 * @param player 
	 * @param action 
	 */
	public void logAction(int round, Player player, String action) {
	}

	/**
	 * 
	 * @param players 
	 */
	public void logVictoryPoints(Player[] players) {
	}
}
