// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Edge[] edges;

	/**
	 * 
	 */
	public void initializeBoard() {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTitleById(int id) {
		return null;
	}

	/**
	 * 
	 * @param id 
	 */
	public void getNodeById(int id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Edge getEdgeById(int id) {
		return null;
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public Node[] getAdjecentNodes(int nodeId) {
		return nodes;
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public Tile[] getAdjecentTiles(int nodeId) {
		return tiles;
	}
}
