// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 * @return 
	 */
	public ResourceCost getCost() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
		return 0;
	}
}
