// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 * @return 
	 */
	public int roll() {
		return 0;
	}

	/**
	 * 
	 * @return 
	 */
	public int rollSingleDie() {
		return 0;
	}
}
