// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
public class GameSimulator {
	/**
	 * 
	 */
	private int currentRound = 0;
	/**
	 * 
	 */
	private int maxRounds = 1;
	/**
	 * 
	 */
	private boolean gameOver = false;

	/**
	 * 
	 */
	public void intializeGame() {
	}

	/**
	 * 
	 */
	public void runSimulation() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkWinCondition() {
		return gameOver;
	}

	/**
	 * 
	 */
	public void printGameState() {
	}

	/**
	 * 
	 * @param filename 
	 */
	public void loadConfiguration(boolean filename) {
	}
}
