// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulator;

/************************************************************/
/**
 * 
 */
class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private String Name;
	/**
	 * 
	 */
	private int VictoryPoint = 0;

	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
		return VictoryPoint;
	}

	/**
	 * 
	 * @return 
	 */
	public int calculateVictoryPoints() {
		return VictoryPoint;
	}

	/**
	 * 
	 * @param board 
	 */
	public void takeTurn(Board board) {
	}

	/**
	 * 
	 * @param diceRoll 
	 * @param board 
	 */
	public void collectResources(int diceRoll, Board board) {
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public boolean buildSettlement(Node node) {
		return false;
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public boolean buildCity(Node node) {
		return false;
	}

	/**
	 * 
	 * @param edge 
	 * @return 
	 */
	public boolean buildRoad(Edge edge) {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean hasMoreThan7Cards() {
		return false;
	}

	/**
	 * 
	 * @param board 
	 */
	public void tryToBuild(Board board) {
	}
}
